# Generated by Django 4.2.6 on 2024-04-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_domain', models.CharField(max_length=255)),
                ('year_founded', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('size_range', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('linked_in_url', models.CharField(max_length=255)),
                ('current_employee_est', models.CharField(max_length=255)),
                ('total_employee_est', models.CharField(max_length=255)),
            ],
        ),
    ]
