# Generated by Django 4.2.6 on 2024-04-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_data', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='companies',
            index=models.Index(fields=['country'], name='upload_data_country_1c5efb_idx'),
        ),
        migrations.AddIndex(
            model_name='companies',
            index=models.Index(fields=['locality'], name='upload_data_localit_0f1789_idx'),
        ),
    ]
