# Generated by Django 4.2.6 on 2024-04-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalyst_user',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
